version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'


  course-catalog-service:
    build: .
    container_name: course_catalog_service
    depends_on:
      - postgres       #DB starts first
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/courses
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - '8080:8080'
