spring:
  application:
    name: course-catalog-service
  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/courses #for docker approach
    # url: jdbc:postgresql://localhost:5432/courses # for brew approach
    username: postgres
    password: postgres
  jpa:
      #database: h2
#      hibernate:
#        ddl-auto: update
      #database-platform: org.hibernate.dialect.H2Dialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop #this recreates the db, not recommended for prod
        #just for testing purposes
      show-sql: true #just for debugging purposes, not for prod
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
  h2:
      console:
        enabled: true
        path: /h2-console
message: Hello from default profile
#
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: prod
#message: Hello from prod profile
#
#---
#
#spring:
#  config:
#    activate:
#      on-profile: non-prod
#message: Hello from non-prod profile