apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: course-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: course.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: course-catalog-service
                port:
                  number: 80
