#apiVersion: v1
#kind: Service
#metadata:
#  name: course-catalog-service
#spec:
#  type: ClusterIP
#  #ClusterIP = internal container network only (no published port).
#  selector:
#    app: course-catalog-service
#  ports:
#    - port: 80
#      targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: course-catalog-service
spec:
  type: NodePort
  selector:
    app: course-catalog-service
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
