name: Docker Image CI

on:
  push:
    branches: [ "pipeline-test" ]
  pull_request:
    branches: [ "pipeline-test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag course-catalog-service:$(date +%s)
