name: Demo Variable Workflow

on:
  push:
    branches:
      - test_variable

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_VAR: ${{ vars.TEST_VARIABLE }}

    steps:
      - name: Print variable
        run: echo "Env var:$MY_VAR"
